### ISSUE TITLE
Add footer containing credit to Jexactyl

### ISSUE THREAD

**Issue by cmrxnn** [h-panel/hPanel#3]
If you're going to make a fork, it's usually common practise to include the credit for where you've taken the code from. In all of hPanel's codebase, Jexactyl is mentioned once in the README. It would be appreciated if the credits were to be reinstated (in the footer of frontend pages). Thanks for your time.

![image](https://user-images.githubusercontent.com/72230943/187101808-1dc3e3fa-0f2b-438b-9630-70c07adf1781.png)

**Comment by LiquidInteract** [comment]
+1 i gotta agree

**Comment by Dishit79** [comment]
+1 it's a common courtesy that should be maintained

**Comment by Shersha01** [comment]
+1 gonna agree

**Comment by devnote-dev** [comment]
Please respect the work of others. +1

**Comment by Moonythegreat** [comment]
+1 dont plagarize

**Comment by JamieGrimwood** [comment]
I’ve taken down yours and others plagiarised “work” many times before, add the credits or I’ll help Jex take this project down for good, every step of the way.

**Comment by gscoutis** [comment]
+1 pls don’t discredit people that put hard time and work into a project

**Comment by TheFallenSpirit** [comment]
+1 Jexactyl is an amazing project, Cam has done lots of work on it to make it an amazing fork of Pterodactyl. An MIT License does not specify you need to credit the author, however it's just a nice thing to do.

**Comment by literally1984** [comment]
i agree you should always give credit to the person who made the project. its only common courtesy and you're a braindead skid if you dont do so.

**Comment by NeroGizmoUwU** [comment]
If you fork someones software its always great to credit person to make it and not claim it as yours,

**Comment by lucatolton** [comment]
+1 without jexactyl this wouldn't be a thing so at least give credit to the project

**Comment by babyharpsea** [comment]
+1

**Comment by chirag350** [comment]
+1

**Comment by b4dsk** [comment]
Footer has been re added in 0.5.2

**Comment by Hyflod** [comment]
+1

**Comment by literally1984** [comment]
jex ftw 🥵

**Comment by trisout78** [comment]
+1

**Comment by TacticianTilted** [comment]
+1

**Comment by camwhi-te** [comment]
This should be reopened considering it _still_ has not been done.

"Footer has been re added in 0.5.2" - Though the latest repository commit literally shows you **removing the credit from the auth page.**
